### PR TITLE
Update to Lightning 3.2.0

### PR DESCRIPTION
**Pull request by balsama**
Made a few changes to make this possible:

* Install contrib projects directly in docroot
* Removed committed patch #2652850
* Updated patch for #2873287 to one that applies to 8.6
* Refactored all profile info files to be compliant with the new API
* Removed the user.role.administrator config which is being provided _somewhere_ else

### CODE REVIEW

**Comment by saltednut** [comment]
I'm not sure why the PR's keep failing like this. One idea might be to just edit the job removing the key as I believe this was a legacy thing that Devin added at one point.

**Comment by balsama** [comment]
Did it just start today? Possibly related to the Enterprise Github subscription that was just started and the need to auth against Acquia now.

I don't know if we have any docs on this tough 😬

**Comment by saltednut** [comment]
Maybe? Can you pull in my latest change? It seems to be passing without api keys. https://travis-ci.org/acquia/df/builds/437307412

**Comment by balsama** [comment]
Not sure about those config errors in the sub-sub-profiles. It installs locally for me.

**Pull request merged**
