### PR TITLE
Added the views_block_filter_block to df_tools_blocks

### PR DESCRIPTION
**Pull request by saltednut**
I think the overrides they do to Views might still be a little too loose even after this patch but unsure where to debug the usesExposedFormInBlock() override.

Perhaps we could also add to the patch with a check here http://cgit.drupalcode.org/views_block_filter_block/tree/src/Plugin/views/vbfbPluginDisplayBlock.php?h=8.x-1.x#n31 ?

Or maybe it doesn't matter.

### CODE REVIEW

**Comment by mortenson** [comment]
In my testing, the patch from https://www.drupal.org/node/2681947#comment-11726095 also allows this to work and doesn't require the contrib module/patch. Would it be acceptable to just patch core to allow this?

**Comment by saltednut** [comment]
Lets switch to the core patch. Can you update the PR and I'll test it?

**Comment by mortenson** [comment]
PR is ready for review (again).

**Comment by saltednut** [comment]
Kind of forcing this in but it resolves some pretty big site building issues with such a small change I think we're good.

**Pull request merged**
