### PR TITLE
Adds update to write to a drushrc.php

### PR DESCRIPTION
**Pull request by typhonius**

### CODE REVIEW

**Comment by saltednut** [comment]
We have an install.sh for this repo, may need to create the drushrc.php file and symlink to a writeable location on that one too.

**Comment by saltednut** [comment]
https://github.com/acquia/df/blob/8.x-1.x/install.sh

**Comment by typhonius** [comment]
@brantwynn if demo_framework pulls this in, do we need symlinks etc in both repos?

**Comment by saltednut** [comment]
Not everyone uses the private repo. So, yes.

**Comment by typhonius** [comment]
Thanks @brantwynn I've rebased this.

**Pull request merged**
