### PR TITLE
Added better support for inline editing of image fields.

### PR DESCRIPTION
**Pull request by mortenson**
This PR adds the experimental module [Quickedit Image](https://github.com/mortenson/quickedit_image) to our build, as well as a bit of custom code that overrides Quickedit Image methods to allow for existing File browsing. As there is no config changes included in this PR, you can test this out by simply copying df_tools_frontend and quickedit_image to your existing build, and enabling df_tools_frontend.

### CODE REVIEW

**Comment by briancwald** [comment]
My initial QA, this works good. @mortenson can we set this to be off by default so we can merge and @brantwynn can create release with it in there (off)

**Comment by mortenson** [comment]
After speaking with @brantwynn it sounds like this won't get merged either way, so we'll have to wait until after this release is complete to merge.

**Comment by briancwald** [comment]
Because it has a conflict or because timing?

**Comment by mortenson** [comment]
Timing

**Comment by saltednut** [comment]
We can merge after I have tested this and push it to the next release,
which should be next week or shortly thereafter.

On Fri, Jul 8, 2016 at 10:40 AM, Samuel Mortenson notifications@github.com
wrote:

> Timing
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/acquia/df/pull/16#issuecomment-231393931, or mute
> the thread
> https://github.com/notifications/unsubscribe/ABDTPqxX9mOhelBKh5ZCMfR8b1nJw5oaks5qTm92gaJpZM4JHKbF
> .

## 

_Brant Wynn_Technical Lead, Presales | _Acquia
http://www.acquia.com/?utm_source=Email&utm_medium=Signature&utm_content=Acquia.com&utm_campaign=Acquia%2BEmail%2BSignature_
_O:_ +1 617-588-9933 | _M:_ +1 312-607-9430 | @brantwynn
http://twitter.com

[image: Save the data for Engage 2016]
https://engage.acquia.com/?utm_source=acquia&utm_medium=email&utm_campaign=email_signature[image:
Acquia Named a Leader in New Gartner Magic Quadrant]
https://www.acquia.com/wcm/gartner-magic-quadrant?utm_source=acquia&utm_medium=email&utm_campaign=email_signature

**Comment by mortenson** [comment]
From https://www.drupal.org/node/2421427, it sounds like this is going to make it into core, which is crazy. I think we should hold off on this until that happens.

**Comment by wimleers** [comment]
Why is it crazy? :D

**Comment by mortenson** [comment]
Crazy awesome? Crazy fast? All the good kinds of crazy.

**Comment by mortenson** [comment]
I haven't gotten word that this functionality get into 8.x-2.x, so I've updated this PR to use the the core patch. This is ready for review again, if we want this in before 8.x-3.x (~6 months out).

**Pull request merged**
