### PR TITLE
Added config rewrite for the Video

### PR DESCRIPTION
**Pull request by saltednut**
Media default display to remove title and author by default

### CODE REVIEW

**Comment by kevinfunk** [comment]
The displays are still showing. It is possible that the file is being overridden?

**Comment by saltednut** [comment]
Sorry, I should have mentioned you'll need to enable the module if testing with the `df` profile.  I tried enabling it and actually saw an issue where we are installing `core.entity_view_mode.media.media_browser` in addition to Lightning installing it, which is weird to me? Anyway, I moved it into /rewrite - this may be an artifact of how the old system was set up before we had sub profiles.

**Comment by saltednut** [comment]
Ok actually... as you can see from the earlier failing tests, this was set up correctly to work with subprofiles of df.  So in order to test this, rather than doing `drush si df` then `drush en df_tools_media` you'll want to do `drush si dfs_dev` and then check for the changes in configuration either by looking at `/admin/structure/media/manage/video/display` or simply inspecting it via drush `drush cget core.entity_view_display.media.video.default`

**Review by kevinfunk — COMMENTED** [review]
It worked on dfs_dev

**Pull request merged**
