### PR TITLE
Fix "Map" block type and add basic tests for Hero and Map types

### PR DESCRIPTION
**Pull request by mortenson**
This PR adds two new tests for our more complicated blocks, with the idea that in the future all of our blocks will have coverage. Since the Slideshow, Media, and Content Block types are going to change soon, I have not added tests for those. When they are refactored tests will be added.

I've also ported a previously private module to df_tools_map, which includes the Map block type and plugins that can be used to geocode and filter content that uses geofields.

### CODE REVIEW

**Comment by mortenson** [comment]
@brantwynn Where should these tests live? DF as a profile doesn't require df_tools_blocks, so tests will never pass in the main scenario.

**Comment by saltednut** [comment]
@mortenson maybe we should just enable df_tools_blocks with df_admin?

**Comment by mortenson** [comment]
To test all the blocks, we would have to also enable df_tools_slideshow and df_tools_map. There could be other optional modules in df as well, so I'm not sure what our best practice is for enabling those.

**Comment by saltednut** [comment]
I think these blocks, the map and slideshow are all pretty critical to the demos and we need to be testing them all at this low level. Go for it.

**Pull request merged**
